### PR TITLE
Enable polling vote

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Review by hexonaut — APPROVED** [review]
I originally excluded this as the polling emitter is summed up off chain anyways, but I guess there is no harm in including the option. Changes look good and tests are passing. I would recommend fixing some of the indentation. It looks like you fixed it in some places, but almost every `function` declaration in `VoteDelegate.t.sol` is one-space off.

**Comment by gbalabasquer** [comment]
> I originally excluded this as the polling emitter is summed up off chain anyways, but I guess there is no harm in including the option. Changes look good and tests are passing. I would recommend fixing some of the indentation. It looks like you fixed it in some places, but almost every `function` declaration in `VoteDelegate.t.sol` is one space off.

Ah yes you are right, we could still make the delegator to vote and account the MKR is in their delegation contract. The only benefit this way is they do not need to change anything about the process.
Fixed the identation.

**Review by hexonaut — APPROVED** [review]
I'm okay with merging this in. There is really no harm.

**Comment by hexonaut** [comment]
Do we want to add events to the voting? I added some in the audit PR. Would be worthwhile to have this be consistent.

**Pull request merged**
