### PR TITLE
Add ability to do permissionless free after expiration

### PR DESCRIPTION
**Pull request by brianmcmichael**
Based on https://github.com/makerdao/vote-delegate/pull/1

Adds the ability to allow for permissionless removals of MKR from the chief after the delegation has expired.

This would prevent large amounts of delegated MKR from being stuck in the chief that is ineligible to vote by allowing a keeper to extract MKR from the chief and return it to the stakers.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Unfortunately this doesn't work as expected as it is so simple to avoid this enforcement. The `usr` will just not give IOU approval to the proxy or will move them to another place. That's why `DssGov` has the concept of active MKR as a separate thing of deposited one.
The only way to keep it simple as it is not giving the IOUs to the owner of the MKR.

**Comment by gbalabasquer** [comment]
Well if it's thought in the sense that the MKR owner wants to have this active, then maybe is fine. But this is similar approach to what Kurt proposed and IMO won't be used that much.

**Comment by brianmcmichael** [comment]
> The only way to keep it simple as it is not giving the IOUs to the owner of the MKR.

Has this been discussed? Is there a reason to return the IOU to the owner? Presumably they're passive participants anyways, and I almost feel like they're less likely to get lost if they stay here.

**Comment by hexonaut** [comment]
Yeah we discussed it in the original meeting I believe. Passing through the IOU is useful if we end up adding any rewards program later that requires locking up the IOU. Maybe it won't happen, but it's good to keep our options open imo.

**Comment by brianmcmichael** [comment]
Not doing.

**Pull request closed without merging**
